### ISSUE TITLE
Update for Wrath Classic

### ISSUE THREAD

**Issue by boktai1000** [r0ska/getlink-tbc#1]
Hey! Been using Getlink-TBC for all of TBC without issue, and coming to see if you plan to release an update for Wrath Classic. We're currently in pre-patch and I'm realizing how much I relied on this the past year or so.

Thank you!

**Comment by r0ska** [comment]
https://github.com/r0ska/getlink-tbc/releases/tag/getlink-wotlk-340 & https://github.com/r0ska/getlink-tbc/tree/wotlk
