### ISSUE TITLE
GetLinkWOTLK - Lua Errors with Wrath Classic Phase 2 Game Client 3.4.1

### ISSUE THREAD

**Issue by boktai1000** [r0ska/getlink-tbc#2]
With the release of patch 3.4.1 for Wrath Classic, it seems GetLink has unfortunately been hit with compatibility issues and no longer functions. Passing along information for troubleshooting and making it known.

```
4x GetLinkWOTLK/GetLinkWOTLK.lua:60: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@GetLinkWOTLK/GetLinkWOTLK.lua"]:60: in function `GetLink_Command'
[string "@GetLinkWOTLK/GetLinkWOTLK.lua"]:32: in function `?'
[string "@FrameXML/ChatFrame.lua"]:4938: in function <FrameXML/ChatFrame.lua:4884>
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@FrameXML/ChatFrame.lua"]:4601: in function <FrameXML/ChatFrame.lua:4600>
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@FrameXML/ChatFrame.lua"]:4637: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:121_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:121_OnEnterPressed"]:1>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1
```

```
477x GetLinkWOTLK/GetLinkWOTLK.lua:95: attempt to index global 'GLTable' (a nil value)
[string "@GetLinkWOTLK/GetLinkWOTLK.lua"]:95: in function `AddItem'
[string "@GetLinkWOTLK/GetLinkWOTLK.lua"]:111: in function <GetLinkWOTLK/GetLinkWOTLK.lua:100>

Locals:
idnum = 50
(*temporary) = nil
(*temporary) = "50"
(*temporary) = "4OLDInitiate's Belt"
(*temporary) = "%s%s"
(*temporary) = "4"
(*temporary) = "OLDInitiate's Belt"
(*temporary) = "4OLDInitiate's Belt"
(*temporary) = 5
(*temporary) = 10
(*temporary) = "attempt to index global 'GLTable' (a nil value)"
tc = <table> {
 ffffff = "4"
 9d9d9d = "5"
 00ccff = "7"
 a335ee = "1"
 e6cc80 = "8"
 ff8000 = "6"
 1eff00 = "3"
 0070dd = "2"
}
```

**Comment by r0ska** [comment]
Updated the addon for Ulduar (3.4.1) patch. If you're still getting errors, try running `/gldev purge` & then `/reload`

**Comment by boktai1000** [comment]
Unfortunately after running 3.4.1 and wiping the slate clean in SavedVariables, running a `/gldev build` & `/reload` as well as a `/gldev purge` & `/reload` both outcomes land with Lua error bombs :(

Can be replicated with a fresh setup of GetLinkWOTLK_341.zip

Reviewing the commits, it seems like the itemID was increased, but lots of addons broke in 3.4.1 - I won't claim to know what changes happened under the hood but I think it's something a bit deeper than a few new items, if that helps any

**Comment by r0ska** [comment]
I think I found the problem.

`(*temporary) = "attempt to index global 'GLTable' (a nil value)"`
`(*temporary) = "table expected, got nil"`
 
(╯°□°)╯︵ nil

I've made rookie mistake when "updating" this addon from TBC to WOTLK. One argument in WOTLK version was still referring to TBC; that's why GLTable never got initialized. Sadly I only did testing with my non-fresh setup 😭

```
if event == "ADDON_LOADED" and arg1 == "GetLinkTBC" then
	if not GLOptions or GLOptions["Version"] ~= nVersion then
		GLTable = {}
		...
		...
```

**Comment by r0ska** [comment]
Minifix is out! https://github.com/r0ska/getlink-tbc/releases/tag/getlink-wotlk-341-minifix

I've changed arg1 to wotlk one + made new github release. Hopefully this fixes the problem!

If not; hit me up and i'll investigate more tomorrow when my brain is less dead.

**Comment by boktai1000** [comment]
Seems to be working now!! Thank you so much for looking further and for allowing this addon to continue working into Wrath!
